# .github/workflows/ci.yml

# Continuous Integration (CI) Workflow
name: backend-ci

# Workflow will run whenever a push commit or pull request to the main branch.
on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend-api/**'
  push:
    branches:
      - main
    paths:
      - 'backend-api/**'

# CI workflow jobs
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest+
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend-api/package-lock.json

      - name: Install node dependencies and run Tests
        run: |
          cd backend-api/
          npm install-ci-test
